<p style="background: yellow; font-color:green;">Hi, This is {{ $data['to_mail'] }}</p>
<p style=" font-color:green;">Hello {{ $data['from_mail'] }}.</p>
<p style=" font-color:blue;">{{ $data['subject'] }}.</p>
<p style=" font-color:green;">I'm{{ $data['name'] }}.</p>
<p style=" font-color:blue;">I have some query like {{ $data['message'] }}.</p>
<p style=" font-color:blue;">{{ $data['address_line_1'] }}.</p>
<p style=" font-color:blue;">{{ $data['address_line_2'] }}.</p>
<p style=" font-color:blue;">{{ $data['address_line_3'] }}.</p>
<p  style=" font-color:blue;">{{ $data['address_line_4'] }}.</p>
<p  style=" font-color:blue;">{{ $data['contact_number'] }}.</p>